spring:
  application:
    name: base-backend
  server:
    port: 8080
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  sql:
    init:
      mode: always